# https://github.com/jimschubert/labeler-action

enable:
  issues: false
  prs: true

comments:
  prs: 'Labels have been automatically applied based on the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) and [personal commit rules](https://blog.lumir.page/docs/conventions/git/convention-of-git-commit-message).🏷️'

labels:
  'build':
    include:
      - '^build\b'
  'chore':
    include:
      - '^chore\b'
  'ci':
    include:
      - '^ci\b'
  'design':
    include:
      - '^design\b'
  'docs':
    include:
      - '^docs\b'
  'feat':
    include:
      - '^feat\b'
  'fix':
    include:
      - '^fix\b'
  'perf':
    include:
      - '^perf\b'
  'refactor':
    include:
      - '^refactor\b'
  'remove':
    include:
      - '^remove\b'
  'rename':
    include:
      - '^rename\b'
  'style':
    include:
      - '^style\b'
  'test':
    include:
      - '^test\b'
  'release':
    include:
      - '^release\b'
