lumirlumir/lumirlumir-configs:
  - source: ./.github/sync-client.yml
    dest: ./clients/lumirlumir-configs.yml
  # ./.github/workflows
  - source: ./.github/workflows/lint.yml
    dest: ./configs/.github/workflows/lint.yml
  - source: ./.github/workflows/sync-client.yml
    dest: ./configs/.github/workflows/sync-client.yml
  # ./.github
  - source: ./.github/dependabot.yml
    dest: ./configs/.github/dependabot.yml
  # ./.husky
  - source: ./.husky/pre-commit
    dest: ./configs/.husky/pre-commit
  # ./.vscode/settings.json
  - source: ./.vscode/settings.json
    dest: ./configs/.vscode/settings.json
  # ./
  - source: ./.editorconfig
    dest: ./configs/.editorconfig
  - source: ./.eslintignore
    dest: ./configs/.eslintignore
  - source: ./.eslintrc.js
    dest: ./configs/.eslintrc.js
  - source: ./.markdownlint.json
    dest: ./configs/.markdownlint.json
  - source: ./.markdownlintignore
    dest: ./configs/.markdownlintignore
  - source: ./.nvmrc
    dest: ./configs/.nvmrc
  - source: ./.prettierignore
    dest: ./configs/.prettierignore
  - source: ./.prettierrc.js
    dest: ./configs/.prettierrc.js
  - source: ./babel.config.js
    dest: ./configs/babel.config.js
  - source: ./VScode.code-workspace
    dest: ./configs/VScode.code-workspace
