group:
  # .editorconfig
  - files:
      - source: ./configs/.editorconfig
        dest: .editorconfig
    repos: |
      lumirlumir/npm-koregexp
      lumirlumir/npm-textlint-rule-allowed-uris
      lumirlumir/web-blog-data-md
