group:
  # .github/dependabot.yml
  - files:
      - source: ./configs/.github/dependabot.yml
        dest: .github/dependabot.yml
    repos: |
      lumirlumir/npm-filextlint
      lumirlumir/npm-koregexp
      lumirlumir/npm-textlint-rule-allowed-uris
      lumirlumir/web-blog-data-md

  # .editorconfig
  - files:
      - source: ./configs/.editorconfig
        dest: .editorconfig
    repos: |
      lumirlumir/npm-filextlint
      lumirlumir/npm-koregexp
      lumirlumir/npm-textlint-rule-allowed-uris
      lumirlumir/web-blog-data-md

  # .markdownlint.json
  - files:
      - source: ./configs/.markdownlint.json
        dest: .markdownlint.json
    repos: |
      lumirlumir/npm-filextlint
      lumirlumir/npm-koregexp
      lumirlumir/npm-textlint-rule-allowed-uris
      lumirlumir/web-blog-data-md

  # .nvmrc
  - files:
      - source: ./configs/.nvmrc
        dest: .nvmrc
    repos: |
      lumirlumir/npm-filextlint
      lumirlumir/npm-koregexp
      lumirlumir/npm-textlint-rule-allowed-uris
      lumirlumir/web-blog-data-md

  # LICENSE
  - files:
      - source: ./configs/LICENSE
        dest: LICENSE
    repos: |
      lumirlumir/npm-filextlint
      lumirlumir/npm-koregexp
      lumirlumir/npm-textlint-rule-allowed-uris

  # VScode.code-workspace
  - files:
      - source: ./configs/VScode.code-workspace
        dest: VScode.code-workspace
    repos: |
      lumirlumir/npm-filextlint
      lumirlumir/npm-koregexp
      lumirlumir/npm-textlint-rule-allowed-uris
      lumirlumir/web-blog-data-md
