name: sync

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          ASSIGNEES: lumirlumir
          COMMIT_PREFIX: 'sync:'
          PR_BODY: check out [`${{ env.SHORT_SHA }}`](https://github.com/lumirlumir/lumirlumir-configs/commit/${{ github.sha }}) @lumirlumir :hatching_chick:.
